### ISSUE TITLE
Reset & Configuration @ 800 KHz

### ISSUE THREAD

**Issue by mickeyl** [pierremolinaro/acan2517#22]
What's the rational of lowering the SPI frequence to 800 KHz for the reset and configuration phase? I can't find any indication of that necessity in the respective datasheets.

**Comment by pierremolinaro** [comment]
Hello,

The MCP2518FD datasheet, DS20006027B, in note 1 page 69 says "The frequency of SCK has to be less than or equal to 0.85 half the frequency of SYSCLK". In reset and configuration phase, we do not known the actual clock frequency, may be it is 4 MHz. That is why I have lowered the frequency to 800 kHz (yes, it could be 850 kHz).

Pierre

**Comment by mickeyl** [comment]
Excellent. Thanks!
